
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.1 EDK_O.40d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_GPIO_CAMERA_DEVICE_ID,
		XPAR_GPIO_CAMERA_BASEADDR,
		XPAR_GPIO_CAMERA_INTERRUPT_PRESENT,
		XPAR_GPIO_CAMERA_IS_DUAL
	},
	{
		XPAR_GPIO_FIFO_DEVICE_ID,
		XPAR_GPIO_FIFO_BASEADDR,
		XPAR_GPIO_FIFO_INTERRUPT_PRESENT,
		XPAR_GPIO_FIFO_IS_DUAL
	},
	{
		XPAR_LEDS_8BIT_DEVICE_ID,
		XPAR_LEDS_8BIT_BASEADDR,
		XPAR_LEDS_8BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_8BIT_IS_DUAL
	},
	{
		XPAR_LEDS_POSITIONS_DEVICE_ID,
		XPAR_LEDS_POSITIONS_BASEADDR,
		XPAR_LEDS_POSITIONS_INTERRUPT_PRESENT,
		XPAR_LEDS_POSITIONS_IS_DUAL
	},
	{
		XPAR_PUSH_BUTTONS_5BIT_DEVICE_ID,
		XPAR_PUSH_BUTTONS_5BIT_BASEADDR,
		XPAR_PUSH_BUTTONS_5BIT_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_5BIT_IS_DUAL
	},
	{
		XPAR_XPS_FIFO_DATA_DEVICE_ID,
		XPAR_XPS_FIFO_DATA_BASEADDR,
		XPAR_XPS_FIFO_DATA_INTERRUPT_PRESENT,
		XPAR_XPS_FIFO_DATA_IS_DUAL
	}
};


