
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.4 EDK_O.87xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdmacentral.h"

/*
* The configuration table for devices
*/

XDmaCentral_Config XDmaCentral_ConfigTable[] =
{
	{
		XPAR_XPS_CENTRAL_DMA_0_DEVICE_ID,
		XPAR_XPS_CENTRAL_DMA_0_BASEADDR
	}
};


